name: Build HandBrakeCLI Docker Image

on:
    workflow_dispatch:
        inputs:
            version:
                description: "HandBrake version (e.g., 1.9.2, leave empty for latest)"
                required: false
                type: string

jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository_owner }}/HandBrakeCLI
                  tags: |
                      type=raw,value=${{ inputs.version || 'latest' }}  
                      type=raw,value=latest,enable=${{ inputs.version == '' }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      VERSION=${{ inputs.version }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
